/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String active_indicator = "assets/intro/active_indicator.png";
  static const String app_logo = "assets/intro/app_logo.png";
  static const String cancel = "assets/home/cancel.png";
  static const String home_boating = "assets/home/home_boating.png";
  static const String home_camping = "assets/home/home_camping.png";
  static const String home_cycel = "assets/home/home_cycel.png";
  static const String home_fishing = "assets/home/home_fishing.png";
  static const String home_hunting = "assets/home/home_hunting.png";
  static const String home_swip = "assets/home/home_swip.png";
  static const String ic_add = "assets/home/ic_add.png";
  static const String ic_add_image = "assets/home/ic_add_image.png";
  static const String ic_apple = "assets/intro/ic_apple.png";
  static const String ic_back = "assets/home/filter/ic_back.png";
  static const String ic_category = "assets/home/ic_category.png";
  static const String ic_current_location =
      "assets/home/ic_current_location.png";
  static const String ic_dropdown = "assets/home/ic_dropdown.png";
  static const String ic_ellipse = "assets/home/ic_ellipse.png";
  static const String ic_filter = "assets/home/ic_filter.png";
  static const String ic_home = "assets/home/ic_home.png";
  static const String ic_location = "assets/home/ic_location.png";
  static const String ic_location_map = "assets/home/ic_location_map.png";
  static const String ic_map = "assets/home/ic_map.png";
  static const String ic_notification = "assets/home/ic_notification.png";
  static const String ic_profile = "assets/home/ic_profile.png";
  static const String ic_reward = "assets/home/ic_reward.png";
  static const String ic_search = "assets/home/ic_search.png";
  static const String ic_selected_filter =
      "assets/home/filter/ic_selected_filter.png";
  static const String ic_unselect_filter =
      "assets/home/filter/ic_unselect_filter.png";
  static const String inactive_indicator =
      "assets/intro/inactive_indicator.png";
  static const String intro_screen1 = "assets/intro/poster_1.jpg";
  static const String intro_screen2 = "assets/intro/poster_2.jpg";
  static const String intro_screen3 = "assets/intro/poster_3.jpg";
  static const String intro_screen4 = "assets/intro/poster_4.jpg";

  static const String scroll_up = "assets/home/scroll_up.json";
  static const String select_activity = "assets/home/select_activity.png";
  static const String select_activity1 = "assets/home/select_activity1.png";
  static const String select_activity2 = "assets/home/select_activity2.png";
  static const String select_activity3 = "assets/home/select_activity3.png";
  static const String select_activity4 = "assets/home/select_activity4.png";
  static const String select_activity5 = "assets/home/select_activity5.png";
  static const String splash_screen = "assets/intro/splash_screen.png";
}
